Repository Bynder/gathercontent-gather-ui, pull requests merged in 2023-06, with the labels that each got.

#1213 Adding xxs pill
  lib/Pill/PillBase.js
  lib/Pill/common.js
  lib/Pill/stories/Pill.stories.js
Labels: enhancement

#1214 Feature/icon size 24
  lib/Icon/index.js
  lib/Icon/styles.scss
Labels: enhancement

#1215 GC-986 - Fixing icon sizes
  lib/Icon/styles.scss
Labels: bug

#1211 GC-922 its node 18 time
  .github/workflows/chromatic-main.yml
  .github/workflows/chromatic-pr.yml
  .github/workflows/node.js.yml
  .github/workflows/npm-publish.yml
  package-lock.json
Labels: chromatic
